"""price_ticks

Revision ID: 313553bc5d3e
Revises: 
Create Date: 2026-01-19 20:26:54.795202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313553bc5d3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_ticks_id'), 'price_ticks', ['id'], unique=False)
    op.create_index(op.f('ix_price_ticks_ticker'), 'price_ticks', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_ticks_timestamp'), 'price_ticks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_ticks_timestamp'), table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_ticker'), table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_id'), table_name='price_ticks')
    op.drop_table('price_ticks')
    # ### end Alembic commands ###
